// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace VSIXProject
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject.1bad3a0c-5131-4017-b465-aa75f955ec81";
        public const string Name = "VSIXProject";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Chinthana Gunasekara";
        public const string Tags = "";
    }
}
