// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSIXProjectString = "7e37eef9-8cbe-4b10-81f7-66413cd2c9d3";
        public static Guid VSIXProject = new Guid(VSIXProjectString);

        public const string guidVSPackageCommandCodeWindowContextMenuCmdSetString = "0c1acc31-15ac-417c-86b2-eefdc669e8bf";
        public static Guid guidVSPackageCommandCodeWindowContextMenuCmdSet = new Guid(guidVSPackageCommandCodeWindowContextMenuCmdSetString);

        public const string guidImagesString = "68759f95-6f1d-4a77-87ea-192fc8d811f1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyGroupForCommands = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}