// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject2
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject2PackageString = "2a02ac24-a88a-4d4f-a944-f0373d3b0487";
        public static Guid guidVSIXProject2Package = new Guid(guidVSIXProject2PackageString);

        public const string guidVSIXProject2PackageCmdSetString = "1818c514-d10e-496b-9367-5b9dd9bff6cb";
        public static Guid guidVSIXProject2PackageCmdSet = new Guid(guidVSIXProject2PackageCmdSetString);

        public const string guidImagesString = "11292bcb-c51c-4c75-bfc7-360d356cfacc";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}